name: release-test

on:
  release:
    types: [ published ]
  push:
    branches: [ "master" ]

jobs:
    code-quality:
        runs-on: ["ubuntu-latest"]
        steps:
        - uses: actions/checkout@v4
        - name: clippy
          run: cargo clippy --all-targets --all-features
        - name: fmt
          run: cargo fmt --all

    docs:
        runs-on: ["ubuntu-latest"]
        steps:
        - uses: actions/checkout@v4
        - name: rustdoc
          run: cargo doc --workspace
    
    test:
      runs-on: ["ubuntu-latest"]
      steps:
      - uses: actions/checkout@v4
      - name: Run tests
        # skip fileio stuff, because it doesn't seem to work with github CI
        run: cargo test --all --verbose --workspace -- --skip fileio_io

    build:
        runs-on: ["ubuntu-latest"]
        steps:
        - uses: actions/checkout@v4
        - name: Build
          run: cargo build --verbose --workspace --release