name: test-dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  code-quality:
    runs-on: ["ubuntu-latest"]
    steps:
    - uses: actions/checkout@v4
    - name: clippy
      run: cargo clippy --all-targets --all-features
    - name: rustfmt
      run:  cargo fmt --all

  test:
    runs-on: ["ubuntu-latest"]
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      # skip fileio stuff, because it doesn't seem to work with github CI
      run: cargo test --verbose --workspace -- --skip fileio_io
